In [ ]:
import numpy as np
from scipy.stats import truncnorm

def get_truncated_normal(mean=0.5, sd=0.15, low=0, upp=1):
    return truncnorm((low - mean) / sd, (upp - mean) / sd, loc=mean, scale=sd)

def generate_unique_rows(n_people, n_traits, tn, decimals=5):
    unique_rows = []
    while len(unique_rows) < n_people:
        # Generate and round the new row
        new_row = np.round(tn.rvs(n_traits), decimals=decimals)
        # Check for uniqueness (using np.array_equal for exact match)
        if not any(np.array_equal(new_row, row) for row in unique_rows):
            unique_rows.append(new_row)
    return np.array(unique_rows)

# Parameters
n_people = 20
n_traits = 5
tn = get_truncated_normal()

# Generate unique traits
traits = generate_unique_rows(n_people, n_traits, tn)
print("Traits:\n", traits)

# If you also need unique preferences, you can generate them similarly:
preferences = generate_unique_rows(n_people, n_traits, tn)
print("Preferences:\n", preferences)


Traits:
 [[0.44731 0.80012 0.3729  0.52952 0.33253]
 [0.62727 0.51296 0.37674 0.35103 0.18675]
 [0.40255 0.51018 0.57302 0.46143 0.31254]
 [0.37068 0.58139 0.33258 0.23919 0.21324]
 [0.66779 0.44933 0.59827 0.60599 0.35859]
 [0.48082 0.25666 0.6187  0.34406 0.48374]
 [0.23066 0.61685 0.36146 0.60535 0.74363]
 [0.36502 0.6261  0.60447 0.27097 0.34281]
 [0.53534 0.5905  0.31947 0.4449  0.32762]
 [0.19857 0.39793 0.38016 0.42744 0.67232]
 [0.4677  0.64741 0.48358 0.22966 0.48929]
 [0.62227 0.39838 0.23993 0.63463 0.47096]
 [0.40723 0.24059 0.22939 0.43384 0.34549]
 [0.57746 0.68122 0.61066 0.44553 0.41003]
 [0.61178 0.53753 0.54327 0.45929 0.527  ]
 [0.48009 0.36702 0.59133 0.50703 0.76994]
 [0.47179 0.39811 0.62372 0.28431 0.46332]
 [0.61448 0.57824 0.3528  0.54502 0.38569]
 [0.47495 0.56837 0.53285 0.53006 0.46848]
 [0.71636 0.48501 0.36325 0.49937 0.45089]
 [0.58505 0.6669  0.29335 0.38365 0.57748]
 [0.4315  0.661   0.54343 0.55068 0.43626]
 [0.53326 0.6303  0.52802 0.58486 0.24295]
 [

In [6]:
class Man:
    def __init__(self, id, traits, preferences):
        self.id = id
        self.traits = traits
        self.preferences = preferences
    
    def __repr__(self):
        return f"Man {self.id}: Traits={self.traits}, Preferences={self.preferences}"

# Create a list to store all men
men = [Man(i+1, traits[i], preferences[i]) for i in range(n_people)]

# Example: Accessing traits of the first man (m1)
print(men[0].traits)  # This prints the traits of the first person (m1)

# Example: Print all men
for man in men:
    print(man)

[0.44731 0.80012 0.3729  0.52952 0.33253]
Man 1: Traits=[0.44731 0.80012 0.3729  0.52952 0.33253], Preferences=[0.55684 0.39954 0.58129 0.32915 0.8324 ]
Man 2: Traits=[0.62727 0.51296 0.37674 0.35103 0.18675], Preferences=[0.40899 0.54265 0.57262 0.91506 0.41996]
Man 3: Traits=[0.40255 0.51018 0.57302 0.46143 0.31254], Preferences=[0.78293 0.33238 0.53314 0.5728  0.60942]
Man 4: Traits=[0.37068 0.58139 0.33258 0.23919 0.21324], Preferences=[0.57297 0.49219 0.69315 0.39323 0.60385]
Man 5: Traits=[0.66779 0.44933 0.59827 0.60599 0.35859], Preferences=[0.50036 0.5935  0.24411 0.41824 0.6972 ]
Man 6: Traits=[0.48082 0.25666 0.6187  0.34406 0.48374], Preferences=[0.46643 0.82853 0.19204 0.91076 0.6356 ]
Man 7: Traits=[0.23066 0.61685 0.36146 0.60535 0.74363], Preferences=[0.55989 0.60829 0.57593 0.56327 0.35305]
Man 8: Traits=[0.36502 0.6261  0.60447 0.27097 0.34281], Preferences=[0.69603 0.50454 0.40609 0.42481 0.41891]
Man 9: Traits=[0.53534 0.5905  0.31947 0.4449  0.32762], Preferences=[

In [7]:
class Woman:
    def __init__(self, id, traits, preferences):
        self.id = id
        self.traits = preferences  # Traits are set to preferences
        self.preferences = traits  # Preferences are set to traits
    
    def __repr__(self):
        return f"Woman {self.id}: Traits={self.traits}, Preferences={self.preferences}"

# Create a list to store all women
women = [Woman(i+1, traits[i], preferences[i]) for i in range(n_people)]

# Example: Accessing traits of the first woman (w1)
print(women[0].traits)  # This prints the "traits" of the first woman

# Example: Print all women
for woman in women:
    print(woman)


[0.55684 0.39954 0.58129 0.32915 0.8324 ]
Woman 1: Traits=[0.55684 0.39954 0.58129 0.32915 0.8324 ], Preferences=[0.44731 0.80012 0.3729  0.52952 0.33253]
Woman 2: Traits=[0.40899 0.54265 0.57262 0.91506 0.41996], Preferences=[0.62727 0.51296 0.37674 0.35103 0.18675]
Woman 3: Traits=[0.78293 0.33238 0.53314 0.5728  0.60942], Preferences=[0.40255 0.51018 0.57302 0.46143 0.31254]
Woman 4: Traits=[0.57297 0.49219 0.69315 0.39323 0.60385], Preferences=[0.37068 0.58139 0.33258 0.23919 0.21324]
Woman 5: Traits=[0.50036 0.5935  0.24411 0.41824 0.6972 ], Preferences=[0.66779 0.44933 0.59827 0.60599 0.35859]
Woman 6: Traits=[0.46643 0.82853 0.19204 0.91076 0.6356 ], Preferences=[0.48082 0.25666 0.6187  0.34406 0.48374]
Woman 7: Traits=[0.55989 0.60829 0.57593 0.56327 0.35305], Preferences=[0.23066 0.61685 0.36146 0.60535 0.74363]
Woman 8: Traits=[0.69603 0.50454 0.40609 0.42481 0.41891], Preferences=[0.36502 0.6261  0.60447 0.27097 0.34281]
Woman 9: Traits=[0.45757 0.31466 0.51426 0.55568 0.544

In [9]:
print(men[0])
print(women[0])

Man 1: Traits=[0.44731 0.80012 0.3729  0.52952 0.33253], Preferences=[0.55684 0.39954 0.58129 0.32915 0.8324 ]
Woman 1: Traits=[0.55684 0.39954 0.58129 0.32915 0.8324 ], Preferences=[0.44731 0.80012 0.3729  0.52952 0.33253]
